export const eventTypes = {
    BID_UP: 'BID_UP',
    GET_CURRENT_BID_INFO: 'GET_CURRENT_BID_INFO',
    SELL_PLAYER:'SELL_PLAYER',
    GET_BUYERS_INFO:'GET_BUYERS_INFO',
    SKIP_PLAYER:'SKIP_PLAYER'
  };